### ISSUE TITLE
Revisione articoli passati

### ISSUE THREAD

**Issue by longo-andrea** [javascript-tutorial/it.javascript.info#119]
# Revisione articoli passati

Ciao a tutti 👋
Innanzitutto vi ringrazio per il grande supporto che mi state dando nella traduzione del tutorial!

Purtroppo inizialmente ero da solo ed inesperto, quindi i primi articoli tradotti potrebbero contenere degli errori! Per questo ora vorrei iniziare a revisionare i primi articoli. Essendo già stati tradotti non è necessario un forte impegno, si tratta più che altro di revisionarli e sistemare gli eventuali errori.
Mi aiuterebbe molto ricevere il vostro supporto anche in questo, essendo un'operazione di revisione non richiede troppo tempo, potete quindi infilarla nei vostri momenti liberi 😊

**Importante**
Prima di partire con una revisione verificate che non sia già stata effettuata o prenotata. Una volta deciso l'articolo da revisionare notificatelo con un commento (come nel caso degli articoli da tradurre), in questo modo evitiamo sovrapposizioni.

Per quanto riguarda le revisioni, per questo tipo di articoli sarà necessaria una sola approvazione!
La lista degli articoli da revisionare:

### An introduction

* [x] [An Introduction to JavaScript](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/01-getting-started/1-intro) 
* [x] [Manuals and specifications](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/01-getting-started/2-manuals-specifications) 
* [x] [Code editors](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/01-getting-started/3-code-editors) (@Dorin-David ) #176 
* [x] [Developer console](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/01-getting-started/4-devtools) (@pasor1)

### JavaScript Fundamentals

* [x] [Hello, world!](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/01-hello-world) (@longo-andrea )
* [x] [Code structure](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/02-structure) (@longo-andrea )
* [x] [The modern mode, "use strict"](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/03-strict-mode) (@longo-andrea )
* [x] [Variables](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/04-variables) (@longo-andrea )
* [x] [Data types](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/05-types) (@longo-andrea )
* [x] [Interaction: alert, prompt, confirm](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/06-alert-prompt-confirm) (@longo-andrea )
* [x] [Type Conversions](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/07-type-conversions) (@longo-andrea )
* [x] [Basic operators, maths](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/08-operators) (@pasor1)
* [X] [Comparisons](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/09-comparison) (@pasor1)
* [x] [Conditional branching: if, '?'](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/10-ifelse) (@Dorin-David )
* [x] [Logical operators](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/11-logical-operators)(@Dorin-David ) #181
* [x] [Nullish coalescing operator '??'](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/12-nullish-coalescing-operator) (@Dorin-David ) 
* [x] [Loops: while and for](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/13-while-for)(@Dorin-David ) 
* [x] [The "switch" statement](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/14-switch) 
* [x] [Functions](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/15-function-basics) 
* [x] [Function expressions](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/16-function-expressions) 
* [x] [Arrow functions, the basics](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/17-arrow-functions-basics) 
* [x] [JavaScript specials](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/18-javascript-specials) 

### Code quality

* [x] [Debugging in Chrome](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/03-code-quality/01-debugging-chrome) 
* [x] [Coding Style](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/03-code-quality/02-coding-style) 
* [x] [Comments](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/03-code-quality/03-comments) 
* [x] [Ninja code](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/03-code-quality/04-ninja-code) (@longo-andrea) #171 
* [x] [Automated testing with Mocha](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/03-code-quality/05-testing-mocha) (@longo-andrea) #173
* [x] [Polyfills](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/03-code-quality/06-polyfills) (@longo-andrea) #172 

### Objects: the basics

* [x] [Objects](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/04-object-basics/01-object) (@Dorin-David)
* [x] [Object references and copying](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/04-object-basics/02-object-copy) (@pasor1) #182 
* [x] [Garbage collection](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/04-object-basics/03-garbage-collection) 
* [x] [Object methods, "this"](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/04-object-basics/04-object-methods) (@Dorin-David)
* [x] [Constructor, operator "new"](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/04-object-basics/06-constructor-new) (@Dorin-David)
* [x] [Optional chaining '?.'](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/04-object-basics/07-optional-chaining) (@Dorin-David)
* [x] [Symbol type](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/04-object-basics/08-symbol) (@pasor1)
* [x] [Object to primitive conversion](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/04-object-basics/09-object-toprimitive) (@Dorin-David)

### Data types

* [x] [Methods of primitives](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/05-data-types/01-primitives-methods) (@longo-andrea)
* [x] [Numbers](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/05-data-types/02-number) (@longo-andrea)
* [x] [Strings](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/05-data-types/03-string) (@longo-andrea)
* [x] [Arrays](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/05-data-types/04-array) (@Dorin-David ) 
* [x] [Array methods](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/05-data-types/05-array-methods) (@Dorin-David )  
* [x] [Iterables](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/05-data-types/06-iterable) (@Dorin-David )
* [x] [Map and Set](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/05-data-types/07-map-set) (@Dorin-David )
* [x] [WeakMap and WeakSet](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/05-data-types/08-weakmap-weakset) (@Dorin-David )
* [x] [Object.keys, values, entries](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/05-data-types/09-keys-values-entries) (@Dorin-David )
* [x] [Destructuring assignment](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/05-data-types/10-destructuring-assignment) (@Dorin-David )
* [x] [Date and time](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/05-data-types/11-date) (@Dorin-David )
* [x] [JSON methods, toJSON](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/05-data-types/12-json) (@Dorin-David )

**Comment by pasor1** [comment]
Ciao @longo-andrea  e a tutti i contributors,
mi farebbe piacere dare una mano così prendo un po' di dimestichezza con Github, visto che sono gnubbissimo ... infatti qualche mese avevo fatto una pull request su una pagina rivista, ma senza leggere le guidelines per i contributors, chiedo venia :sweat_smile: 
Potrei iniziare con la revisione di [Developer console](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/01-getting-started/4-devtools) se non è ancora stato fatto, quindi proseguire con [Basic operators, maths](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/08-operators) , [Comparisons](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/09-comparison) e [Conditional branching: if, '?'](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/10-ifelse) ... e spero di non fare casini :smile:

**Comment by longo-andrea** [comment]
> Ciao @longo-andrea e a tutti i contributors,
> mi farebbe piacere dare una mano così prendo un po' di dimestichezza con Github, visto che sono gnubbissimo ... infatti qualche mese avevo fatto una pull request su una pagina rivista, ma senza leggere le guidelines per i contributors, chiedo venia 😅
> Potrei iniziare con la revisione di [Developer console](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/01-getting-started/4-devtools) se non è ancora stato fatto, quindi proseguire con [Basic operators, maths](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/08-operators) , [Comparisons](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/09-comparison) e [Conditional branching: if, '?'](https://github.com/javascript-tutorial/it.javascript.info/blob/master/1-js/02-first-steps/10-ifelse) ... e spero di non fare casini 😄

Grazie mille @pasor1 , abbiamo veramente bisogno di aiuto su questo 😄

**Comment by longo-andrea** [comment]
Ciao @pasor1 , grazie dell'aiuto ne abbiamo veramente bisogno 😄 
Certo i tre articoli te li assegno subito cosi siamo sicuri di non intralciarci! 😄 
Se hai piacere di collaborare anche nella fase di approvazione degli articoli, fammelo sapere che ti aggiungo al gruppo dei maintainers! Per qualsiasi dubbio abbiamo anche un canale Discorsd 😄

**Comment by pasor1** [comment]
Mi sono iscritto al canale Discord :wink: 
Ok, per gli articoli che trattano argomenti non troppo avanzati posso dare una mano per le review

**Comment by Dorin-David** [comment]
Come procedo da qui in avanti? Posso prenotare degli articoli da tradurre? Tipo logical operators e loops?

**Comment by longo-andrea** [comment]
Certo, se vuoi tradurre un articolo devi fari riferimento all issue delle traduzioni, basta lasciare un commento con il titolo dell'articolo che vuoi tradurre (se non è già assegnato o tradotto)... In questa issue facciamo revisione dei vecchi articoli che sono stati tradotti un po' malamente.. in entrambi i casi ti ricordo di lavorare su un nuovo branch, per evitare problemi 😊

**Comment by Dorin-David** [comment]
Allora io procedo, intanto, alla revisione del terzo articolo, poi con logical operators. Ho visto che gli articoli fino a logical operators sono tutti prenotati. C'è un modo per essere notificati quando saranno pronti per il merging? Nel caso fosse sfuggito qualcosa. Sono uno pignolo e due occhi in più non fanno male :')
Inoltre, se potete, e ovviamente volete, potete aggiungermi alla lista di quelli che revisionano le pull request. Attualmente studio a tempo pieno, quindi abbastanza tempo a disposizione e un articolo, se non due, al giorno, posso farli. Fatemi sapere @longo-andrea @pasor1 @mean2me 
P.S. E' un piacere collaborare con voi!

**Comment by pasor1** [comment]
Gli articoli che vedi spuntati sono già stati rivisti e "mergiati".
A fianco del titolo dell'articolo trovi il riferimento del contributor che ha avuto, o ha tuttora in carico la traduzione.
Se a fianco del contributor c'è l'hashtag  con il numero della PR, significa che la PR è ancora aperta, in attesa di essere approvata e "mergiata". @Dorin-David  ti ho assegnato l' articolo "logical operators", oltre a #176 . 
Ricordati di lavorare su branch dedicati ad ogni articolo, e di mettere il titolo dell'articolo come intestazione della PR, troverai un po' di consigli sul flusso di lavoro in [CONTRIBUTING](https://github.com/javascript-tutorial/it.javascript.info/blob/master/CONTRIBUTING.md) ed in [README](https://github.com/javascript-tutorial/it.javascript.info/blob/master/README.md). Buon lavoro :wink:

**Comment by longo-andrea** [comment]
> Allora io procedo, intanto, alla revisione del terzo articolo, poi con logical operators. Ho visto che gli articoli fino a logical operators sono tutti prenotati. C'è un modo per essere notificati quando saranno pronti per il merging? Così posso commentare/ dare dei suggerimenti, qualora fossero necessari. Sono uno pignolo e due occhi in più non fanno male :')
> Inoltre, se potete, e ovviamente volete, potete aggiungermi alla lista di quelli che revisionano le pull request. Attualmente studio a tempo pieno, quindi ho abbastanza tempo a disposizione e un articolo, se non due, al giorno, posso farli. Fatemi sapere @longo-andrea @pasor1 @mean2me
> P.S. E' un piacere collaborare con voi!

Oltre a tutto quello che ha detto Simone aggiungo anche la risposta alla tua domanda di essere aggiunto come reviewer... Allora, attualmente tutti possono fare le revisioni delle PR (quindi anche tu sei abilitato a farlo), dopo siamo noi a decidere se accettare le revisioni "estranee" o no... Vedo che con le revisioni stai lavorando molto bene, quindi se decidi di fare revisioni alle PR sono ben accette!
Per quanto riguarda essere "maintainer" l'unico vantaggio in più che avresti sarebbe quello di poter fare il "merge" delle PR... essendo un ruolo un po' delicato aggiungiamo solamente chi conosce bene Git, in modo da evitare problemi vari... Per ora non abbiamo grosse difficoltà a gestire i merge, ma siamo più che altro in carenza di traduttori/revisionatori... quindi per le review delle PR vai pure senza problemi (per evitare conflitti assegnati la PR dal pannellino a destra), mentre per entrare nei "maintainer" vediamo intanto come te la cavi con GitHub poi in caso se ti fa piacere ti aggiungiamo 😄

**Comment by Dorin-David** [comment]
Ottimo, ho capito. Di Git non so nulla, ma voglio impararlo. Al momento giusto, se ve ne sara' bisogno, sara' un piacere fare anche il mantainer. Intanto procedo con le revisioni. Come posso aggiungermi al gruppo Discord? Mi farebbe molto piacere...

**Comment by Dorin-David** [comment]
Posso iniziare la revisione di *loops, while and for*?

**Comment by pasor1** [comment]
Ok, assegnato. Buon lavoro ;-)

**Comment by Dorin-David** [comment]
Ragazzi qualcuno aggiunga l'articolo sul *nullish coalescing operator* sotto quello sui *sui logical operators*. Lo prenoto io per la revisione. Prenoto anche quello sul *conditional branching*. Ricapitolando, penso io ai seguenti (se vi va bene ovviamente):

- conditional branching
-  nullish coalescing operator
- loops: while and for

**Comment by Dorin-David** [comment]
Partirei con la revisione di *switch statement* e *Functions*.

**Comment by Dorin-David** [comment]
Vado con *Function expressions*

**Comment by Dorin-David** [comment]
Vado con *Objects* e *Object methods, "this"*

**Comment by pasor1** [comment]
Faccio Symbol type

**Comment by Dorin-David** [comment]
Vado con *Constructor operator, 'new'*

**Comment by Dorin-David** [comment]
Vado con Optional chaining '?.' e  Object to primitive conversion

**Comment by Dorin-David** [comment]
*Arrays* e *Arrays methods*

**Comment by Dorin-David** [comment]
*Iterables* e *Map and Set*

**Comment by Dorin-David** [comment]
WeakMap and WeakSet
Object.keys, values, entries

**Comment by Dorin-David** [comment]
Destructuring assignment
Date and time
JSON methods, toJSON
